#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      my-cluster-proxy:
        targetCluster:
          bootstrap_servers: my-cluster-kafka-bootstrap:9093
          tls:
            trust:
              storeFile: /opt/kroxylicious/trust/ca.p12
              storePassword:
                filePath: /opt/kroxylicious/trust/ca.password
        clusterNetworkAddressConfigProvider:
          type: SniRouting
          config:
            bootstrapAddress: mycluster-proxy.kafka:9092
            brokerAddressPattern: broker$(nodeId).mycluster-proxy.kafka
        logNetwork: false
        logFrames: false
        tls:
          key:
            storeFile: /opt/kroxylicious/server/key-material/keystore.p12
            storePassword:
              filePath: /opt/kroxylicious/server/keystore-password/storePassword
    filters:
    - type: ApiVersions
