#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
ignored:
  - DL4006
  - SC3010
  - DL3006
  - DL3041
