#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

#integrationtests requires Java 19, exclude from the reactor, see https://community.sonatype.com/t/java-19-supported/10371
setup = "scripts/setupLift.sh"
build = "mvn install -pl !:integrationtests --also-make-dependents"
jdkVersion = "17"