#integrationtests requires Java 19, exclude from the reactor, see https://community.sonatype.com/t/java-19-supported/10371
setup = "scripts/setupLift.sh"
ignoreFiles = """
integrationtests/**
**/test/**
"""

jdkVersion = "17"