#integrationtests requires Java 19, exclude from the reactor, see https://community.sonatype.com/t/java-19-supported/10371
build = "mvn install -pl :krpc-code-gen; mvn -DskipTests=true -pl !integrationtests"
jdkVersion = "17"