#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: Service
metadata:
  name: kroxylicious-service
spec:
  type: NodePort
  selector:
    app: kroxylicious
  ports:
  - name: port-30192
    protocol: TCP
    port: 30192
    targetPort: 30192
    nodePort: 30192

  - name: port-30193
    protocol: TCP
    port: 30193
    targetPort: 30193
    nodePort: 30193

  - name: port-30194
    protocol: TCP
    port: 30194
    targetPort: 30194
    nodePort: 30194

  - name: port-30195
    protocol: TCP
    port: 30195
    targetPort: 30195
    nodePort: 30195

  - name: port-30292
    protocol: TCP
    port: 30292
    targetPort: 30292
    nodePort: 30292

  - name: port-30293
    protocol: TCP
    port: 30293
    targetPort: 30293
    nodePort: 30293

  - name: port-30294
    protocol: TCP
    port: 30294
    targetPort: 30294
    nodePort: 30294

  - name: port-30295
    protocol: TCP
    port: 30295
    targetPort: 30295
    nodePort: 30295
