#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kroxylicious-config
data:
  config.yaml: |
    filters:
    - type: EnvelopeEncryption
      config:
        kms: VaultKmsService
        kmsConfig:
          vaultUrl: http://vault.vault.svc.cluster.local:8200
          vaultToken: myroottoken
        selector: TemplateKekSelector
        selectorConfig:
          template: all
    adminHttp:
      endpoints:
        prometheus: {}
    virtualClusters:
      devenv1:
        targetCluster:
          bootstrap_servers: my-cluster-kafka-bootstrap:9092
        clusterNetworkAddressConfigProvider:
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            bootstrapAddress: minikube:30192
        logNetwork: false
        logFrames: false
