#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroxylicious-proxy
  labels:
    app: kroxylicious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kroxylicious
  template:
    metadata:
      labels:
        app: kroxylicious
    spec:
      containers:
      - name: kroxylicious
        image: quay.io/kroxylicious/kroxylicious:0.3.0-SNAPSHOT
        imagePullPolicy: Always
        args: ["--config", "/opt/kroxylicious/config/config.yaml"]
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kroxylicious/config/config.yaml
          subPath: config.yaml
        - name: server-tls-secret-volume
          readOnly: true
          mountPath: /opt/kroxylicious/server-tls
        - name: kafka-cluster-ca-cert
          readOnly: true
          mountPath: /opt/kroxylicious/trust
      volumes:
      - name: config-volume
        configMap:
          name: kroxylicious-config
      - name: server-tls-secret-volume
        secret:
          secretName: kroxy-server-tls
      - name: kafka-cluster-ca-cert
        secret:
          secretName: my-cluster-cluster-ca-cert
