name: GitHub Pages Publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          source_dir: docs/
          pre_build: "apk add go && go install github.com/asciitosvg/asciitosvg/cmd/a2s@latest && cp ~/go/bin/a2s /usr/local/bin/"
          asciidoctor_params: "-r asciidoctor-diagram"
          post_build: 'find . -name "*.svg" -exec git add -f {} \;'
