name: GitHub Pages Publish
on:
  workflow_run:
    workflows: [Main Push Trigger]
    types: [completed]
concurrency:
  group: ${{ github.workflow }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          source_dir: docs/
          asciidoctor_params: "--require asciidoctor-diagram --attribute=sectlinks --attribute=sectanchors"
          post_build: 'find . -name "*.svg" -exec git add -f {} \;'
